# Generated by Django 4.2.2 on 2023-06-25 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_imagepostmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together={('user', 'post')},
        ),
    ]
