# Generated by Django 4.2.2 on 2023-06-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_likemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(default='0-0'),
        ),
    ]
