# Generated by Django 4.2.2 on 2023-10-11 11:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_recyclepost_postmodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
