# Generated by Django 4.2.2 on 2023-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=73, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=73, null=True)),
                ('last_name', models.CharField(blank=True, max_length=73, null=True)),
                ('bio', models.TextField(blank=True, max_length=730, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
