# Generated by Django 4.2.2 on 2023-06-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reportusermodel_notificationmodel_messagemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationmodel',
            name='allowed',
        ),
    ]
