# Generated by Django 4.2.2 on 2023-07-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recycleuser_alter_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Please upload your image.', null=True, upload_to='users'),
        ),
        migrations.DeleteModel(
            name='ImageUserModel',
        ),
    ]
